In [1]:
%matplotlib inline


What is PyTorch?
================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

-  NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
-  최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Getting Started
---------------

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.



In [2]:
from __future__ import print_function
import torch

torch.__version__

'1.9.1+cu111'

초기화되지 않은 5x3 행렬을 생성합니다:



In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39]])


무작위로 초기화된 행렬을 생성합니다:



In [5]:
x = torch.randn(5, 3) #표준정규분포에서 샘플링하는 것
print(x)
x = torch.rand(5, 3) #0~1사이의 값을 샘플링하는 것
print(x)

tensor([[ 1.9927, -0.7878,  0.6342],
        [-0.1019,  0.5303, -1.1593],
        [ 0.1418,  1.5432,  0.0206],
        [ 2.8912,  0.4303,  0.2716],
        [-2.2295,  0.4997,  0.2315]])
tensor([[0.9110, 0.1982, 0.8906],
        [0.5112, 0.6941, 0.3967],
        [0.1742, 0.2128, 0.0359],
        [0.8860, 0.7558, 0.2320],
        [0.4648, 0.1824, 0.5419]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성합니다:



In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 
이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4662,  0.6106,  0.6764],
        [-0.4464, -0.1958,  0.3140],
        [-1.1860, -0.9838, -0.0473],
        [ 1.0794,  0.5333, -0.8492],
        [ 0.5926, -1.0124,  0.5278]])


행렬의 크기를 구합니다:



In [11]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])



덧셈: 문법1

In [12]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 0.4662,  0.6106,  0.6764],
        [-0.4464, -0.1958,  0.3140],
        [-1.1860, -0.9838, -0.0473],
        [ 1.0794,  0.5333, -0.8492],
        [ 0.5926, -1.0124,  0.5278]])
tensor([[0.1415, 0.2077, 0.7731],
        [0.3950, 0.5327, 0.2100],
        [0.6950, 0.8215, 0.9175],
        [0.8233, 0.3537, 0.6344],
        [0.4842, 0.3372, 0.5483]])
tensor([[ 0.6077,  0.8183,  1.4495],
        [-0.0514,  0.3369,  0.5240],
        [-0.4910, -0.1623,  0.8702],
        [ 1.9026,  0.8870, -0.2148],
        [ 1.0768, -0.6752,  1.0761]])


덧셈: 문법2



In [13]:
print(torch.add(x, y))

tensor([[ 0.6077,  0.8183,  1.4495],
        [-0.0514,  0.3369,  0.5240],
        [-0.4910, -0.1623,  0.8702],
        [ 1.9026,  0.8870, -0.2148],
        [ 1.0768, -0.6752,  1.0761]])


덧셈: 결과 tensor를 인자로 제공


In [14]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38]])
tensor([[ 0.6077,  0.8183,  1.4495],
        [-0.0514,  0.3369,  0.5240],
        [-0.4910, -0.1623,  0.8702],
        [ 1.9026,  0.8870, -0.2148],
        [ 1.0768, -0.6752,  1.0761]])


덧셈: 바꿔치기(In-place) 방식


In [15]:
# adds x to y
print(y)
y.add_(x) #y를 x를 더한 값으로 바꿈
print(y)

tensor([[0.1415, 0.2077, 0.7731],
        [0.3950, 0.5327, 0.2100],
        [0.6950, 0.8215, 0.9175],
        [0.8233, 0.3537, 0.6344],
        [0.4842, 0.3372, 0.5483]])
tensor([[ 0.6077,  0.8183,  1.4495],
        [-0.0514,  0.3369,  0.5240],
        [-0.4910, -0.1623,  0.8702],
        [ 1.9026,  0.8870, -0.2148],
        [ 1.0768, -0.6752,  1.0761]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.<p>
예: x.copy_(y), x.t_() 는 x 를 변경합니다.

<p>
NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!


In [16]:
print(x)
print(x[:, 1])

tensor([[ 0.4662,  0.6106,  0.6764],
        [-0.4464, -0.1958,  0.3140],
        [-1.1860, -0.9838, -0.0473],
        [ 1.0794,  0.5333, -0.8492],
        [ 0.5926, -1.0124,  0.5278]])
tensor([ 0.6106, -0.1958, -0.9838,  0.5333, -1.0124])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:


In [17]:
x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1, 2)  # the size -1 is inferred from other dimensions
print(y)
print(z)
print(y.size(), z.size())

tensor([[ 0.3623, -0.1868,  0.5992, -1.0197],
        [-0.6739, -0.3269,  0.8140,  0.1330],
        [-0.9573,  2.2923,  0.1883,  0.2983],
        [ 0.1093, -1.7960,  0.5059,  1.7409]])
tensor([ 0.3623, -0.1868,  0.5992, -1.0197, -0.6739, -0.3269,  0.8140,  0.1330,
        -0.9573,  2.2923,  0.1883,  0.2983,  0.1093, -1.7960,  0.5059,  1.7409])
tensor([[ 0.3623, -0.1868],
        [ 0.5992, -1.0197],
        [-0.6739, -0.3269],
        [ 0.8140,  0.1330],
        [-0.9573,  2.2923],
        [ 0.1883,  0.2983],
        [ 0.1093, -1.7960],
        [ 0.5059,  1.7409]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.



In [18]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())


tensor([1.1971])
<class 'torch.Tensor'> <class 'float'>
1.1971328258514404


**읽을 거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>` 에 설명되어 있습니다.

NumPy 변환(Bridge)
------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

- Torch Tensor를 NumPy 배열로 변환하기



In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


 - NumPy 배열을 Torch Tensor로 변환하기  
 
NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [23]:
import numpy as np

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

CUDA Tensors
------------

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [24]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

x = torch.rand(4,4)

if torch.cuda.is_available():
    device = "cuda:0" # torch.device("cuda:0")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    print(y)
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.8983, 1.8667, 1.1790, 1.8397],
        [1.9174, 1.9086, 1.5222, 1.8781],
        [1.5301, 1.9978, 1.9021, 1.8556],
        [1.2218, 1.7053, 1.3124, 1.9214]], device='cuda:0')
tensor([[1.8983, 1.8667, 1.1790, 1.8397],
        [1.9174, 1.9086, 1.5222, 1.8781],
        [1.5301, 1.9978, 1.9021, 1.8556],
        [1.2218, 1.7053, 1.3124, 1.9214]], dtype=torch.float64)


In [25]:
x = x.cuda()